import type { Metadata } from 'next';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import NavBar from './components/ui/navBar/NavBar';
import Footer from './components/ui/footer/Footer';


export const metadata: Metadata = {
  title: 'Next Auth',
  description: 'Generated by create next app',
};

interface Prop {
  children: React.ReactNode;
}
const RootLayout = ({ children }: Readonly<Prop>) => {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <NavBar />
          <>
            <main className="pageWith"> {children}</main>
          </>
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
};
export default RootLayout;
